### ISSUE TITLE
Getting error while running piicatcher through file or DB having more records

### ISSUE THREAD

**Issue by jayeshagwan1** [tokern/piicatcher#83] opened 2020-04-01 08:31 UTC
I am trying to run piicatcher on csv file with 15K records and getting below error:

File "f:\pii\piicrawler\.env\lib\site-packages\spacy\language.py", line 429, in __call__                                    Errors.E088.format(length=len(text), max_length=self.max_length)                                                           ValueError: [E088] Text of length 2924092 exceeds maximum of 1000000. The v2.x parser and NER models require roughly 1GB of te mporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not us ing the parser or NER, it's probably safe to increase the `nlp.max_length` limit. The limit is in number of characters, so you  can check whether your inputs are too long by checking `len(text)`.

Is there any limitation for data ?

**Comment by vrajat** [comment] 2020-04-02 04:20
Looks like these are default limits set by [spacy](https://spacy.io). Refer this [question](https://datascience.stackexchange.com/questions/38745/increasing-spacy-max-nlp-limit). 

The real solution is #44 . Right now PIICatcher is considering csv files as one big text file. Instead PIICatcher should parse csv files into rows and columns and check only one column at a time. Then this limit will not be hit.

**Comment by vrajat** [comment] 2020-04-14 09:24
I'll resolve this as a duplicate of #44 as that will solve this issue.

**Closed by vrajat** 2020-04-14 09:24 UTC
Labels: duplicate, support
