### ISSUE TITLE
ERROR:  duplicate key value violates unique constraint "unique_column_name"

### ISSUE THREAD

**Issue by yourssvk** [tokern/piicatcher#162] opened 2021-11-28 06:07 UTC
ERROR:  duplicate key value violates unique constraint "unique_column_name" -> This happens on a brand new catalog db on a redshift deep scan, most likely it requires a better unique key constraint...

**Comment by jhecking** [comment] 2023-05-12 08:22
Duplicate of #164?

**Closed by jhecking** 2023-05-12 08:22 UTC
