### ISSUE TITLE
shallow scan followed by deep scan causes pk/ uk violations (and possibly viceversa)

### ISSUE THREAD

**Issue by yourssvk** [tokern/piicatcher#164] opened 2021-11-29 05:50 UTC
shallow scan followed by deep scan causes pk/ uk violations (and possibly viceversa)

**Comment by vrajat** [comment] 2021-11-29 14:57
I've run shallow and deep scans interchangeably multiple times. Do you have a stack trace or any other information that can be helpful?

**Comment by yourssvk** [comment] 2021-11-29 16:00
Please park this one aside, will get the trace next time...

**Comment by jhecking** [comment] 2023-05-12 08:20
Not able to reproduce. Closing as won't fix.

**Closed** 2023-05-12 08:22 UTC
