### ISSUE TITLE
Unable to read from the oracle DB schema

### ISSUE THREAD

**Issue by GLT-Dashboard** [tokern/piicatcher#129] opened 2021-05-03 16:41 UTC
@vrajat
Hope all are well and doing great!!

Thank you for such a fantastic library

This is what I am facing:

As mentioned on [https://tokern.io/docs/piicatcher/4-aws](https://tokern.io/docs/piicatcher/4-aws) and discovering that "-t" doesn't work for DB selection I was able to find the right selector argument from databases.py which is "--connection-type". Using the same and updating my piicatcher command (BTW running all of this on the ubuntu) i.e., 
piicatcher db -s 192.168._.__ -R 2020 -u REPORT_USER -p ________ -d PLATFORM --connection-type oracle  -c deep -n REPORT_USER
I ran the executor command and these are the errors I am getting for Oracle DB:
![PII_GIT_ERROR_1](https://user-images.githubusercontent.com/77790174/116904549-d7331900-ac0b-11eb-8aa7-679e6ad04597.PNG)

Also tried it using the config file way as mentioned on [https://tokern.io/docs/piicatcher/2-usage](https://tokern.io/docs/piicatcher/2-usage) created the following
 
![cfg_ini_file](https://user-images.githubusercontent.com/77790174/116904985-66403100-ac0c-11eb-85b8-86201240f750.jpg) 

and ran the executor command but still receiving the same error message
![PII_GIT_ERROR_2](https://user-images.githubusercontent.com/77790174/116905055-7f48e200-ac0c-11eb-8f5c-ddd07fa20448.PNG)

Please do take a look and let me know if there is anything I need to update on my end

**Comment by vrajat** [comment] 2021-05-04 04:03
This error is w.r.t to printing in a tabular format in the terminal. Can you try `--catalog-format json --catalog-file <path>`? This will output the results in json format.

**Comment by vrajat** [comment] 2021-05-04 04:08
Thanks for pointing out that `-t` is overloaded. I'll file a new issue. Thanks!

**Comment by GLT-Dashboard** [comment] 2021-05-04 05:06
@vrajat, Thanks a lot for the prompt response.. 

Could you please provide additional inputs on how to utilize --catalog-format json --catalog-file <path> ?? 
Do I have to append it to the db read string " piicatcher db -s ________ -R 2020 -u REPORT_USER -p _________ -d PLATFORM -c shallow --connection-type oracle -n REPORT_USER" ??

**Comment by vrajat** [comment] 2021-05-04 05:09
Yes. Add these two options to the existing command line.

**Comment by rusq** [comment] 2021-05-04 05:14
@GLT-Dashboard, hey man, what does this has to do with me or other people you mentioned, except, maybe Rajat?  Did you just go and pick random people from the issue/pr list?

**Comment by GLT-Dashboard** [comment] 2021-05-04 12:31
> @GLT-Dashboard, hey man, what does this has to do with me or other people you mentioned, except, maybe Rajat? Did you just go and pick random people from the issue/pr list?

Yes you are right just thought since you all worked on the issues earlier, would be easier to get more replies on the issue being faced, was impressed by the amazing issues created and resolved by you all, but never the less I have modified my previous comment, sorry to bother.

**Comment by GLT-Dashboard** [comment] 2021-05-04 12:31
> Yes. Add these two options to the existing command line.

Thank you @vrajat

**Comment by GLT-Dashboard** [comment] 2021-05-05 04:54
Hey @vrajat as directed in your previous comment I did try both these commands below
This is the sample data we tried running the piicatcher on both oracle as well as file based
![InkedMicrosoftTeams-image (1)_LI](https://user-images.githubusercontent.com/77790174/117098270-f9c44f80-ad3b-11eb-9c96-d5d32887bbe5.jpg)

**1st**- 
piicatcher --catalog-format json --catalog-file results.json db -s 192.168._.__ -R 2020 -u REPORT_USER -p ******* -d PLATFORM -c shallow --connection-type oracle -n REPORT_USER -t SAMPLE_PII
But getting this:
![InkedMicrosoftTeams-image (4)_LI](https://user-images.githubusercontent.com/77790174/117098259-f204ab00-ad3b-11eb-8a1d-bf72c1f3aef9.jpg)

**2nd**-
piicatcher --catalog-format json --catalog-file results.json --config cfg.ini db
But getting this:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/77790174/117098074-6e4abe80-ad3b-11eb-851e-5a00ef116c83.png)

Please do take a look and let us know if we are doing any blunder in executing these. Also if possible can you please take a look at this documentation on [https://tokern.io/docs/piicatcher/5-databases](https://tokern.io/docs/piicatcher/5-databases) looks like some execution related information is missing or maybe are just riding on the wrong train.

Thank you @vrajat

**Comment by vrajat** [comment] 2021-05-06 02:00
Can you share the CSV of the sample data? I'll check it out.

**Comment by GLT-Dashboard** [comment] 2021-05-06 03:09
Hi @vrajat,
 
I was unable to upload the CSV file.. Please find the google drive link as below - 
https://docs.google.com/spreadsheets/d/1ww48ta9gntw5xL1KY1OEiay1RrwLBjZou-ASQ1eNU0I/edit?usp=sharing

I am also attaching the .xlsx format - 
[PII_df.xlsx](https://github.com/tokern/piicatcher/files/6431473/PII_df.xlsx)

The same sample data was pushed to Oracle database under a separate schema and this was listed in the config file as shown above..

**Comment by vrajat** [comment] 2021-05-07 08:00
I tried out the sample file and you can see the results in [this line](https://github.com/tokern/piicatcher/pull/131/files#diff-1a0296dda6f2354dbd684ffe949ff0338a913bf6d144d68b6ec300cff357f6c9R72) I am getting relevant output. So this is somehow related to oracle. It is working on postgres.

I dont have access to oracle. Can you run piicatcher with debug logging? Add `--log-level DEBUG` Please sanitize the logs of any sensitive information and share it.

**Comment by GLT-Dashboard** [comment] 2021-05-07 08:10
Good afternoon, Rajat.. I will execute as you have suggested, by adding the log level.. Alternatively, I will also push the same sample data to Postgres. Also, can you please share the screenshot, so that I can have a reference?? 
Thanks!

**Comment by vrajat** [comment] 2021-05-07 09:10
The output is in the link I provided in the previous comment.

**Comment by vrajat** [comment] 2021-05-07 09:12
Another possible problem is that the following query in Oracle is not returning any results. You have to run piicatcher with an admin user.


        SELECT
            '{db}', TABLE_NAME, COLUMN_NAME
        FROM
            USER_TAB_COLUMNS
        WHERE UPPER(DATA_TYPE) LIKE '%CHAR%'
        ORDER BY TABLE_NAME, COLUMN_ID

(replace {db} with PLATFORM)

**Comment by GLT-Dashboard** [comment] 2021-05-07 09:55
@vrajat ,
1. In the DEBUG mode, I was able to read the column headers from the Oracle DB, however, the output file still came up blank.
2. Replacing [db] with PLATFORM gave me missing command error. 

Anything else I could check?? Am I missing something here??

**Comment by vrajat** [comment] 2021-05-07 09:57
1. Can you attach the logs?
2. Did you enclose PLATFORM in quotes?

**Comment by GLT-Dashboard** [comment] 2021-05-07 10:06
@vrajat ,

1. These are the logs - piicatcher --log-level DEBUG --catalog-format json --catalog-file results.json --config cfg.ini db

![Capture1](https://user-images.githubusercontent.com/77790174/117433580-42048d00-af49-11eb-9e60-5b8cfb102b2b.JPG)

2. I enclosed PLATFORM in quotes within the config file, I got an error as -> Error reading configuration file: Invalid line (''PLATFORM'') (matched as neither section nor keyword) at line 1.
3. I used PLATFORM in place of db on the command line with double quotes, it gave me a read error.

This library is addressing the problem statement to a large extent, that's the reason we are trying our best to make this work!

**Comment by vrajat** [comment] 2021-05-07 10:23
never mind about PLATFORM. I've got my answer from the screenshot. Can you share the log file?

**Comment by GLT-Dashboard** [comment] 2021-05-07 10:33
@vrajat , Which log file are you referring to?? Please let me know the path.. Is it created by log_mixin.py??

**Comment by vrajat** [comment] 2021-05-07 10:35
the logs from log_mixin. Redirect it to a file and attach it. 

    piicatcher --log-level DEBUG ... > log_file 2>&1

**Comment by GLT-Dashboard** [comment] 2021-05-07 11:09
Attaching the log file - 

[log_file.LOG](https://github.com/tokern/piicatcher/files/6441075/log_file.LOG)

**Comment by GLT-Dashboard** [comment] 2021-05-07 11:11
@vrajat , Attaching the log file - 

[log_file.txt](https://github.com/tokern/piicatcher/files/6441078/log_file.txt)

**Comment by vrajat** [comment] 2021-05-07 16:35
Are there more logs after this? If not, that is a problem. For example, I get logs that look like below:

    DEBUG    piicatcher.log_mixin.Schema:metadata.py:82 Scanning public
    DEBUG    piicatcher.log_mixin.Table:metadata.py:82 Scanning sample_2
    DEBUG    piicatcher.log_mixin.Column:metadata.py:154 Scanning column name Social Security number
    DEBUG    root:scanner.py:98 PiiTypes are PiiTypes.SSN
    DEBUG    piicatcher.log_mixin.Column:metadata.py:154 Scanning column name addedfromui
    DEBUG    root:scanner.py:98 PiiTypes are 
    DEBUG    piicatcher.log_mixin.Column:metadata.py:154 Scanning column name address
    DEBUG    root:scanner.py:98 PiiTypes are PiiTypes.ADDRESS
    DEBUG    piicatcher.log_mixin.Column:metadata.py:154 Scanning column name asset_id
    DEBUG    root:scanner.py:98 PiiTypes are 
    DEBUG    piicatcher.log_mixin.Column:metadata.py:154 Scanning column name city

**Comment by vrajat** [comment] 2021-05-07 16:39
Why have you added `-n REPORT_USER`? That is the problem. You should remove it from the command line.

**Comment by GLT-Dashboard** [comment] 2021-05-08 12:00
@vrajat , There are no more additional logs, I sent u the entire log file.. Also, -n REPORT_USER was added to scan only that particular schema, & within that schema, I have created the sample_PII table..

**Comment by vrajat** [comment] 2021-05-11 03:02
There is definitely some problem there with -n. It is excluding tables or schemas from scanning. I'll have to try to reproduce it.

**Comment by GLT-Dashboard** [comment] 2021-05-13 14:44
@vrajat ,
1. We have pushed the same data to Postgres DB, as shown below : 

<img width="960" alt="capture2" src="https://user-images.githubusercontent.com/77790174/118141472-070dc800-b427-11eb-8cec-88208e26da64.png">

2. This is the log file as attached for the Postgres DB. 

[log_file.txt](https://github.com/tokern/piicatcher/files/6473125/log_file.txt)

3. Or alternatively, can we run the test_sample.py file as shown in this chore https://github.com/tokern/piicatcher/pull/131 ??

**Comment by vrajat** [comment] 2021-05-14 07:13
in the postgres log file - its a connection issue. its not the same issue as the oracle one. 

To run the sample file, you will have to setup a development environment. Instructions are here: https://tokern.io/docs/piicatcher/development
Instructions work on an ubuntu (or most linux variants) and mac.

**Comment by vrajat** [comment] 2021-05-14 07:27
Re-iterating that your command line is wrong. From the oracle logs: 

    DEBUG:piicatcher.log_mixin.Database:Name: database, include: (REPORT_USER), exclude: ()
    DEBUG:piicatcher.log_mixin.Schema:Name: PLATFORM, include: (), exclude: ()

You have specified it to include `REPORT_USER` schema. However piicatcher only finds `PLATFORM` schema. So it doesnt include `PLATFORM` schema. You should fix your command line to test with oracle. 

With postgres, you have connection issues. You should first make sure that you can connect to postgres using `psql`. Then test out PIICatcher.

**Comment by vrajat** [comment] 2021-05-17 04:50
Closing this issue because I believe I have helped you identify the wrong usage of command line parameters with Oracle. Also the connection issue with postgres is not an issue within PIICatcher. Please open a new issue once you fix these and if piicatcher is still not working for you.

**Closed by vrajat** 2021-05-17 04:50 UTC
Labels: support
